version: '3.9'

networks:
      Inception_network:
            name: Inception_network
            driver: bridge

volumes:
      volume_DB:
            driver: local
            name: volume_DB
            driver_opts:
                  type: none
                  o: bind
                  device: /home/rkaufman/data/DB
#                 for testing on School Mac only
#                  device: /Users/rkaufman/Projects/DB
      volume_WordPress:
            driver: local
            name: volume_WordPress
            driver_opts:
                  type: none
                  o: bind
                  device: /home/rkaufman/data/WordPress
#                 for testing on School Mac only
#                  device: /Users/rkaufman/Projects/WordPress

services:
      service_nginx:
            container_name: nginx
            image: nginx
            build: requirements/nginx
            depends_on:
                  - service_wordpress
            ports:
                  - "443:443"
            volumes:
                  - volume_WordPress:/var/www/html
            environment:
                  - PS1
            networks:
                  - Inception_network
            restart: on-failure

      service_wordpress:
            container_name: wordpress
            image: wordpress
            build: requirements/wordpress
            depends_on:
                  - service_mariadb
            # ports:
            #       - 9000:9000
            volumes:
                  - volume_WordPress:/var/www/html:rw
            environment:
                  - PS1
                  - WORDPRESS_DB_HOST
                  - WORDPRESS_DB_USER
                  - WORDPRESS_DB_PASSWORD
                  - WORDPRESS_DB_NAME
            networks:
                  - Inception_network
            restart: on-failure

      service_mariadb:
            container_name: mariadb
            image: mariadb
            build: requirements/mariadb
            # ports:
            #       - 3306:3306
            volumes:
                  - volume_DB:/var/lib/mysql:rw
            environment:
                  - PS1
                  - MYSQL_ROOT_PASSWORD
                  - MYSQL_USER
                  - MYSQL_PASSWORD
                  - MYSQL_DATABASE
                  - WORDPRESS_DB_USER
                  - WORDPRESS_DB_PASSWORD
                  - WORDPRESS_DB_NAME
            networks:
                  - Inception_network
            restart: on-failure

#BONUS
      service_website:
            container_name: website
            image: website
            build: requirements/bonus/website
            volumes:
                  - volume_WordPress:/var/www/html:rw
            environment:
                  - PS1
            networks:
                  - Inception_network
            restart: on-failure

      service_ftp:
            container_name: ftp
            image: ftp
            build: requirements/bonus/ftp
            ports:
                  - 20:20
                  - 21:21
                  - 12000:12000
            volumes:
                  - volume_WordPress:/home/rkaufman/ftp:rw
            environment:
                  - PS1
                  - FTP_USER
                  - FTP_PASS
            networks:
                  - Inception_network
            restart: on-failure

      service_adminer:
            container_name: adminer
            image: adminer
            build: requirements/bonus/adminer
            volumes:
                  - volume_WordPress:/var/www/html:rw
            environment:
                  - PS1
            networks:
                  - Inception_network
            restart: on-failure